---
:accessibility: Not wheelchair accessible.
:address: 1641 LaSalle Ave. San Francisco, CA 94124
:contact_name: Keesha Henry, Program Director
:description: Our Father’s SLE (OFSLE) provides service-structured, low-cost transitional
  housing to recovering men who have become displaced as a result of substance abuse
  and addiction.  Located in the Bayview Community, our home is designed to assist
  recovering men at the transitional and community re-entry phases of their recovery
  and our length of stay ranges from 6 months up to 1 year.
:eligible_population: Adult men, 18 years or older, with special outreach to veterans,
  seniors, parolees, and GBQT who have become homeless as a result of substance abuse/addiction.
:email: keeshahenry@gmail.com
:faith_based: No.
:fax: 
:fees: 
:languages:
- English
:miscellaneous: |-
  Days and Hours: Monday-Friday, 9:00am to 5:00pm for intakes.
  Notes: Appointments required.
  Client fees: Shared rooms are $600/month.
:name: Our Father’s Sober Living Environment
:phone: "(415) 926-0258"
:services:
- Transitional Housing
- Food/Prepared Meals
- Hygiene/Personal Care Items
- P.O. Box/ Mail Service
- Mental Health Treatment
- Substance Abuse Treatment
- Community Education & Mediation
- Outreach
- Post-Incarceration Support
- Referrals to other resources available as needed
:url: www.cleanlounge.info
:what_to_bring: California ID and any letters of recommendation or personal references
  to support your application to our program.
:__meta__:
  :version: 0.0.1
